# Exploration des données

## Importation des données

In [10]:
import pandas as pd
import s3fs

BUCKET = "xifar19"
FILE_KEY_S3 = "boardgames/bgg_dataset.csv"
FILE_PATH_S3 = f"{BUCKET}/{FILE_KEY_S3}"

fs = s3fs.S3FileSystem()

with fs.open(FILE_PATH_S3, mode="rb") as file_in:
    df = pd.read_csv(file_in, sep=";")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20343 entries, 0 to 20342
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  20327 non-null  float64
 1   Name                20343 non-null  object
 2   Year Published      20342 non-null  float64
 3   Min Players         20343 non-null  int64
 4   Max Players         20343 non-null  int64
 5   Play Time           20343 non-null  int64
 6   Min Age             20343 non-null  int64
 7   Users Rated         20343 non-null  int64
 8   Rating Average      20343 non-null  object
 9   BGG Rank            20343 non-null  int64
 10  Complexity Average  20343 non-null  object
 11  Owned Users         20320 non-null  float64
 12  Mechanics           18745 non-null  object
 13  Domains             10184 non-null  object
dtypes: float64(3), int64(6), object(5)
memory usage: 2.2+ MB

In [22]:
df.head()

,ID,Name,Year Published,Min Players,Max Players,Play Time,Min Age,Users Rated,Rating Average,BGG Rank,Complexity Average,Owned Users,Mechanics,Domains
0,174430.0,Gloomhaven,2017.0,1,4,120,14,42055,"8,79",1,"3,86",68323.0,"Action Queue, Action Retrieval, Campaign / Bat...","Strategy Games, Thematic Games"
1,161936.0,Pandemic Legacy: Season 1,2015.0,2,4,60,13,41643,"8,61",2,"2,84",65294.0,"Action Points, Cooperative Game, Hand Manageme...","Strategy Games, Thematic Games"
2,224517.0,Brass: Birmingham,2018.0,2,4,120,14,19217,"8,66",3,"3,91",28785.0,"Hand Management, Income, Loans, Market, Networ...",Strategy Games
3,167791.0,Terraforming Mars,2016.0,1,5,120,12,64864,"8,43",4,"3,24",87099.0,"Card Drafting, Drafting, End Game Bonuses, Han...",Strategy Games
4,233078.0,Twilight Imperium: Fourth Edition,2017.0,3,6,480,14,13468,"8,70",5,"4,22",16831.0,"Action Drafting, Area Majority / Influence, Ar...","Strategy Games, Thematic Games"

ID est une colonne d'ID propre à BGG, à voir si je garde pour intégrer des images.

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20343 entries, 0 to 20342
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  20327 non-null  float64
 1   Name                20343 non-null  object
 2   Year Published      20342 non-null  float64
 3   Min Players         20343 non-null  int64
 4   Max Players         20343 non-null  int64
 5   Play Time           20343 non-null  int64
 6   Min Age             20343 non-null  int64
 7   Users Rated         20343 non-null  int64
 8   Rating Average      20343 non-null  object
 9   BGG Rank            20343 non-null  int64
 10  Complexity Average  20343 non-null  object
 11  Owned Users         20320 non-null  float64
 12  Mechanics           18745 non-null  object
 13  Domains             10184 non-null  object
dtypes: float64(3), int64(6), object(5)
memory usage: 2.2+ MB

Je remarque qu'il manque 16 valeurs dans la colonne ID, environ 600 valeurs dans la colonne Mechanics et environs 10 000 valeurs dans la colonne Domains.
Je vais d'office supprimer les enregistrements où les valeurs sont manquantes dans la colonne ID

In [13]:
df_na=df[df['ID'].isna()]

In [21]:
df_na['ID'].size

16

In [15]:
df_clean=df.dropna(subset='ID')

In [16]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20327 entries, 0 to 20342
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  20327 non-null  float64
 1   Name                20327 non-null  object
 2   Year Published      20327 non-null  float64
 3   Min Players         20327 non-null  int64
 4   Max Players         20327 non-null  int64
 5   Play Time           20327 non-null  int64
 6   Min Age             20327 non-null  int64
 7   Users Rated         20327 non-null  int64
 8   Rating Average      20327 non-null  object
 9   BGG Rank            20327 non-null  int64
 10  Complexity Average  20327 non-null  object
 11  Owned Users         20320 non-null  float64
 12  Mechanics           18745 non-null  object
 13  Domains             10184 non-null  object
dtypes: float64(3), int64(6), object(5)
memory usage: 2.3+ MB

In [17]:
df_clean.head()

,ID,Name,Year Published,Min Players,Max Players,Play Time,Min Age,Users Rated,Rating Average,BGG Rank,Complexity Average,Owned Users,Mechanics,Domains
0,174430.0,Gloomhaven,2017.0,1,4,120,14,42055,"8,79",1,"3,86",68323.0,"Action Queue, Action Retrieval, Campaign / Bat...","Strategy Games, Thematic Games"
1,161936.0,Pandemic Legacy: Season 1,2015.0,2,4,60,13,41643,"8,61",2,"2,84",65294.0,"Action Points, Cooperative Game, Hand Manageme...","Strategy Games, Thematic Games"
2,224517.0,Brass: Birmingham,2018.0,2,4,120,14,19217,"8,66",3,"3,91",28785.0,"Hand Management, Income, Loans, Market, Networ...",Strategy Games
3,167791.0,Terraforming Mars,2016.0,1,5,120,12,64864,"8,43",4,"3,24",87099.0,"Card Drafting, Drafting, End Game Bonuses, Han...",Strategy Games
4,233078.0,Twilight Imperium: Fourth Edition,2017.0,3,6,480,14,13468,"8,70",5,"4,22",16831.0,"Action Drafting, Area Majority / Influence, Ar...","Strategy Games, Thematic Games"