# Exploration des données

## Importation des données

In [27]:
import pandas as pd
import s3fs

In [ ]:
BUCKET = "xifar19"
FILE_KEY_S3 = "boardgames/bgg_dataset.csv"
FILE_PATH_S3 = f"{BUCKET}/{FILE_KEY_S3}"

fs = s3fs.S3FileSystem()

with fs.open(FILE_PATH_S3, mode="rb") as file_in:
    df = pd.read_csv(file_in, sep=";")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20343 entries, 0 to 20342
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  20327 non-null  float64
 1   Name                20343 non-null  object
 2   Year Published      20342 non-null  float64
 3   Min Players         20343 non-null  int64
 4   Max Players         20343 non-null  int64
 5   Play Time           20343 non-null  int64
 6   Min Age             20343 non-null  int64
 7   Users Rated         20343 non-null  int64
 8   Rating Average      20343 non-null  object
 9   BGG Rank            20343 non-null  int64
 10  Complexity Average  20343 non-null  object
 11  Owned Users         20320 non-null  float64
 12  Mechanics           18745 non-null  object
 13  Domains             10184 non-null  object
dtypes: float64(3), int64(6), object(5)
memory usage: 2.2+ MB

In [22]:
df.head()

,ID,Name,Year Published,Min Players,Max Players,Play Time,Min Age,Users Rated,Rating Average,BGG Rank,Complexity Average,Owned Users,Mechanics,Domains
0,174430.0,Gloomhaven,2017.0,1,4,120,14,42055,"8,79",1,"3,86",68323.0,"Action Queue, Action Retrieval, Campaign / Bat...","Strategy Games, Thematic Games"
1,161936.0,Pandemic Legacy: Season 1,2015.0,2,4,60,13,41643,"8,61",2,"2,84",65294.0,"Action Points, Cooperative Game, Hand Manageme...","Strategy Games, Thematic Games"
2,224517.0,Brass: Birmingham,2018.0,2,4,120,14,19217,"8,66",3,"3,91",28785.0,"Hand Management, Income, Loans, Market, Networ...",Strategy Games
3,167791.0,Terraforming Mars,2016.0,1,5,120,12,64864,"8,43",4,"3,24",87099.0,"Card Drafting, Drafting, End Game Bonuses, Han...",Strategy Games
4,233078.0,Twilight Imperium: Fourth Edition,2017.0,3,6,480,14,13468,"8,70",5,"4,22",16831.0,"Action Drafting, Area Majority / Influence, Ar...","Strategy Games, Thematic Games"

ID est une colonne d'ID propre à BGG, à voir si je garde pour intégrer des images.

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20343 entries, 0 to 20342
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  20327 non-null  float64
 1   Name                20343 non-null  object
 2   Year Published      20342 non-null  float64
 3   Min Players         20343 non-null  int64
 4   Max Players         20343 non-null  int64
 5   Play Time           20343 non-null  int64
 6   Min Age             20343 non-null  int64
 7   Users Rated         20343 non-null  int64
 8   Rating Average      20343 non-null  object
 9   BGG Rank            20343 non-null  int64
 10  Complexity Average  20343 non-null  object
 11  Owned Users         20320 non-null  float64
 12  Mechanics           18745 non-null  object
 13  Domains             10184 non-null  object
dtypes: float64(3), int64(6), object(5)
memory usage: 2.2+ MB

Je remarque qu'il manque 16 valeurs dans la colonne ID, environ 600 valeurs dans la colonne Mechanics et environs 10 000 valeurs dans la colonne Domains.
Je vais d'office supprimer les enregistrements où les valeurs sont manquantes dans la colonne ID

In [13]:
df_na=df[df['ID'].isna()]

In [21]:
df_na['ID'].size

16

In [15]:
df_clean=df.dropna(subset='ID')

In [16]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20327 entries, 0 to 20342
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  20327 non-null  float64
 1   Name                20327 non-null  object
 2   Year Published      20327 non-null  float64
 3   Min Players         20327 non-null  int64
 4   Max Players         20327 non-null  int64
 5   Play Time           20327 non-null  int64
 6   Min Age             20327 non-null  int64
 7   Users Rated         20327 non-null  int64
 8   Rating Average      20327 non-null  object
 9   BGG Rank            20327 non-null  int64
 10  Complexity Average  20327 non-null  object
 11  Owned Users         20320 non-null  float64
 12  Mechanics           18745 non-null  object
 13  Domains             10184 non-null  object
dtypes: float64(3), int64(6), object(5)
memory usage: 2.3+ MB

In [ ]:
df_clean.head()

,ID,Name,Year Published,Min Players,Max Players,Play Time,Min Age,Users Rated,Rating Average,BGG Rank,Complexity Average,Owned Users,Mechanics,Domains
0,174430.0,Gloomhaven,2017.0,1,4,120,14,42055,"8,79",1,"3,86",68323.0,"Action Queue, Action Retrieval, Campaign / Bat...","Strategy Games, Thematic Games"
1,161936.0,Pandemic Legacy: Season 1,2015.0,2,4,60,13,41643,"8,61",2,"2,84",65294.0,"Action Points, Cooperative Game, Hand Manageme...","Strategy Games, Thematic Games"
2,224517.0,Brass: Birmingham,2018.0,2,4,120,14,19217,"8,66",3,"3,91",28785.0,"Hand Management, Income, Loans, Market, Networ...",Strategy Games
3,167791.0,Terraforming Mars,2016.0,1,5,120,12,64864,"8,43",4,"3,24",87099.0,"Card Drafting, Drafting, End Game Bonuses, Han...",Strategy Games
4,233078.0,Twilight Imperium: Fourth Edition,2017.0,3,6,480,14,13468,"8,70",5,"4,22",16831.0,"Action Drafting, Area Majority / Influence, Ar...","Strategy Games, Thematic Games"

In [24]:
df_clean['Mechanics'].value_counts()

Mechanics
Hand Management                                                                                                 432
Hexagon Grid                                                                                                    412
Dice Rolling                                                                                                    372
Roll / Spin and Move                                                                                            369
Tile Placement                                                                                                  285
                                                                                                               ...
Area Movement, Hidden Movement, Secret Unit Deployment, Team-Based Game                                           1
Auction/Bidding, Auction: Sealed Bid, Constrained Bidding, Pick-up and Deliver, Time Track, Worker Placement      1
Area Majority / Influence, Mancala, Tile Placement                                                                1
Area Majority / Influence, Campaign / Battle Card Driven, Rock-Paper-Scissors, Trading                            1
Memory, Player Elimination, Role Playing, Variable Player Powers                                                  1
Name: count, Length: 7381, dtype: int64

In [25]:
df_clean['Domains'].value_counts()

Domains
Wargames                                          3029
Strategy Games                                    1455
Family Games                                      1340
Abstract Games                                     869
Children's Games                                   708
Thematic Games                                     647
Party Games                                        409
Family Games, Strategy Games                       354
Customizable Games                                 235
Strategy Games, Thematic Games                     217
Thematic Games, Wargames                           139
Family Games, Party Games                          139
Abstract Games, Family Games                       116
Family Games, Thematic Games                       109
Children's Games, Family Games                     105
Strategy Games, Wargames                            99
Abstract Games, Strategy Games                      40
Party Games, Thematic Games                         36
Customizable Games, Strategy Games                  26
Abstract Games, Children's Games                    23
Customizable Games, Wargames                        18
Customizable Games, Thematic Games                  15
Abstract Games, Wargames                            13
Party Games, Strategy Games                          7
Children's Games, Party Games                        6
Family Games, Wargames                               5
Strategy Games, Thematic Games, Wargames             5
Children's Games, Wargames                           4
Abstract Games, Party Games                          4
Abstract Games, Customizable Games                   2
Children's Games, Family Games, Party Games          2
Family Games, Thematic Games, Wargames               1
Family Games, Party Games, Thematic Games            1
Family Games, Strategy Games, Thematic Games         1
Party Games, Wargames                                1
Customizable Games, Thematic Games, Wargames         1
Abstract Games, Children's Games, Wargames           1
Abstract Games, Strategy Games, Thematic Games       1
Abstract Games, Thematic Games                       1
Name: count, dtype: int64

## Enrichissement avec des images

In [35]:
BUCKET = "xifar19"
FILE_KEY_S3 = "boardgames/bgg_pictures.csv"
FILE_PATH_S3 = f"{BUCKET}/{FILE_KEY_S3}"

fs = s3fs.S3FileSystem()

with fs.open(FILE_PATH_S3, mode="rb") as file_in:
    df_pictures = pd.read_csv(file_in, sep=",", engine="python", on_bad_lines="warn")

Je vais essayer de join l'url des images

In [37]:
df_pictures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10532 entries, 0 to 10531
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   game_id         10532 non-null  int64
 1   description     10532 non-null  object
 2   image           10531 non-null  object
 3   max_players     10532 non-null  int64
 4   max_playtime    10532 non-null  int64
 5   min_age         10532 non-null  int64
 6   min_players     10532 non-null  int64
 7   min_playtime    10532 non-null  int64
 8   name            10532 non-null  object
 9   playing_time    10532 non-null  int64
 10  thumbnail       10531 non-null  object
 11  year_published  10532 non-null  int64
 12  artist          7759 non-null   object
 13  category        10438 non-null  object
 14  compilation     410 non-null    object
 15  designer        10406 non-null  object
 16  expansion       2752 non-null   object
 17  family          7724 non-null   object
 18  mechanic        9582 non-null   object
 19  publisher       10529 non-null  object
 20  average_rating  10532 non-null  float64
 21  users_rated     10532 non-null  int64
dtypes: float64(1), int64(9), object(12)
memory usage: 1.8+ MB

In [41]:
df_join=df_clean.merge(df_pictures,left_on='ID', right_on='game_id')

In [42]:
df_join.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10386 entries, 0 to 10385
Data columns (total 36 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  10386 non-null  float64
 1   Name                10386 non-null  object
 2   Year Published      10386 non-null  float64
 3   Min Players         10386 non-null  int64
 4   Max Players         10386 non-null  int64
 5   Play Time           10386 non-null  int64
 6   Min Age             10386 non-null  int64
 7   Users Rated         10386 non-null  int64
 8   Rating Average      10386 non-null  object
 9   BGG Rank            10386 non-null  int64
 10  Complexity Average  10386 non-null  object
 11  Owned Users         10380 non-null  float64
 12  Mechanics           9664 non-null   object
 13  Domains             6974 non-null   object
 14  game_id             10386 non-null  int64
 15  description         10386 non-null  object
 16  image               10385 non-null  object
 17  max_players         10386 non-null  int64
 18  max_playtime        10386 non-null  int64
 19  min_age             10386 non-null  int64
 20  min_players         10386 non-null  int64
 21  min_playtime        10386 non-null  int64
 22  name                10386 non-null  object
 23  playing_time        10386 non-null  int64
 24  thumbnail           10385 non-null  object
 25  year_published      10386 non-null  int64
 26  artist              7644 non-null   object
 27  category            10297 non-null  object
 28  compilation         293 non-null    object
 29  designer            10265 non-null  object
 30  expansion           2707 non-null   object
 31  family              7596 non-null   object
 32  mechanic            9448 non-null   object
 33  publisher           10384 non-null  object
 34  average_rating      10386 non-null  float64
 35  users_rated         10386 non-null  int64
dtypes: float64(4), int64(15), object(17)
memory usage: 2.9+ MB

On perd la moitié des données en inner join, faire un left join

In [58]:
df_join=df_clean.merge(df_pictures[['game_id','image', 'artist','designer','publisher']],left_on='ID', right_on='game_id',how="left")

In [47]:
df_join.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20327 entries, 0 to 20326
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  20327 non-null  float64
 1   Name                20327 non-null  object
 2   Year Published      20327 non-null  float64
 3   Min Players         20327 non-null  int64
 4   Max Players         20327 non-null  int64
 5   Play Time           20327 non-null  int64
 6   Min Age             20327 non-null  int64
 7   Users Rated         20327 non-null  int64
 8   Rating Average      20327 non-null  object
 9   BGG Rank            20327 non-null  int64
 10  Complexity Average  20327 non-null  object
 11  Owned Users         20320 non-null  float64
 12  Mechanics           18745 non-null  object
 13  Domains             10184 non-null  object
 14  game_id             10386 non-null  float64
 15  image               10385 non-null  object
 16  artist              7644 non-null   object
 17  designer            10265 non-null  object
 18  publisher           10384 non-null  object
dtypes: float64(4), int64(6), object(9)
memory usage: 2.9+ MB

## Enrichissement avec le dump de BGG

In [57]:
BUCKET = "xifar19"
FILE_KEY_S3 = "boardgames/boardgames_ranks.csv"
FILE_PATH_S3 = f"{BUCKET}/{FILE_KEY_S3}"

fs = s3fs.S3FileSystem()

with fs.open(FILE_PATH_S3, mode="rb") as file_in:
    df_ranks = pd.read_csv(file_in, sep=",", engine="python", on_bad_lines="warn")

In [49]:
df_ranks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176913 entries, 0 to 176912
Data columns (total 16 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   176913 non-null  int64
 1   name                 176913 non-null  object
 2   yearpublished        176913 non-null  int64
 3   rank                 176913 non-null  int64
 4   bayesaverage         176913 non-null  float64
 5   average              176913 non-null  float64
 6   usersrated           176913 non-null  int64
 7   is_expansion         176913 non-null  int64
 8   abstracts_rank       1498 non-null    float64
 9   cgs_rank             380 non-null     float64
 10  childrensgames_rank  1128 non-null    float64
 11  familygames_rank     3600 non-null    float64
 12  partygames_rank      979 non-null     float64
 13  strategygames_rank   3246 non-null    float64
 14  thematic_rank        1817 non-null    float64
 15  wargames_rank        4560 non-null    float64
dtypes: float64(10), int64(5), object(1)
memory usage: 21.6+ MB

In [59]:
df_join=df_join.merge(df_ranks[['id','abstracts_rank','cgs_rank','childrensgames_rank','familygames_rank','partygames_rank','strategygames_rank','thematic_rank','wargames_rank']],
how="left",left_on="ID",right_on="id")

In [ ]:
df_join.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20327 entries, 0 to 20326
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   20327 non-null  float64
 1   Name                 20327 non-null  object
 2   Year Published       20327 non-null  float64
 3   Min Players          20327 non-null  int64
 4   Max Players          20327 non-null  int64
 5   Play Time            20327 non-null  int64
 6   Min Age              20327 non-null  int64
 7   Users Rated          20327 non-null  int64
 8   Rating Average       20327 non-null  object
 9   BGG Rank             20327 non-null  int64
 10  Complexity Average   20327 non-null  object
 11  Owned Users          20320 non-null  float64
 12  Mechanics            18745 non-null  object
 13  Domains              10184 non-null  object
 14  game_id              10386 non-null  float64
 15  image                10385 non-null  object
 16  artist               7644 non-null   object
 17  designer             10265 non-null  object
 18  publisher            10384 non-null  object
 19  id                   20300 non-null  float64
 20  abstracts_rank       1210 non-null   float64
 21  cgs_rank             343 non-null    float64
 22  childrensgames_rank  994 non-null    float64
 23  familygames_rank     3033 non-null   float64
 24  partygames_rank      886 non-null    float64
 25  strategygames_rank   2693 non-null   float64
 26  thematic_rank        1526 non-null   float64
 27  wargames_rank        3582 non-null   float64
dtypes: float64(13), int64(6), object(9)
memory usage: 4.3+ MB

In [61]:
df_join.columns

Index(['ID', 'Name', 'Year Published', 'Min Players', 'Max Players',
       'Play Time', 'Min Age', 'Users Rated', 'Rating Average', 'BGG Rank',
       'Complexity Average', 'Owned Users', 'Mechanics', 'Domains', 'game_id',
       'image', 'artist', 'designer', 'publisher', 'id', 'abstracts_rank',
       'cgs_rank', 'childrensgames_rank', 'familygames_rank',
       'partygames_rank', 'strategygames_rank', 'thematic_rank',
       'wargames_rank'],
      dtype='object')

In [65]:
df_join['image'].sample(10)

2060      //cf.geekdo-images.com/images/pic501309.jpg
1983     //cf.geekdo-images.com/images/pic1732644.jpg
4717     //cf.geekdo-images.com/images/pic1316284.jpg
340      //cf.geekdo-images.com/images/pic2537618.jpg
9923                                              NaN
1288       //cf.geekdo-images.com/images/pic55922.jpg
16690                                             NaN
5380                                              NaN
3005      //cf.geekdo-images.com/images/pic145572.jpg
18891    //cf.geekdo-images.com/images/pic1801430.jpg
Name: image, dtype: object

In [66]:
import requests

url = "https://cf.geekdo-images.com/images/pic59279.jpg"
headers = {
    "User-Agent": "Mozilla/5.0",
    "Referer": "https://boardgamegeek.com/"
}

r = requests.get(url, headers=headers, timeout=20)
print("status:", r.status_code)
print("content-type:", r.headers.get("content-type"))
print("first-bytes:", r.content[:20])

status: 403
content-type: application/xml
first-bytes: b'<?xml version="1.0" '

Je n'ai pas accès à l'image, il faut passer par l'API je pense...